import type { CatalogItem } from "./catalog";

/*
 * Starter ingredients from two Thai homebrew shops, taken from their ingredient pages in Sept 2026:
 *  - WAS Homebrew: washomebrew.com, "วัตถุดิบ" category
 *  - Craft Components: craft.co.th, all malt, hop, yeast and additive collections
 *
 * Malt colors are the shop's EBC, using the middle of a range. Potential comes from the maltster's
 * "extract (dry basis)" where the shop lists it; otherwise it is a typical value. Hop alpha acid is
 * the middle of the shop's range, with the range and crop year kept in notes. When a hop is sold
 * for several crop years, the newest one is used. Yeast attenuation and flocculation come from the
 * yeast maker's data (Fermentis "sedimentation" maps to flocculation).
 *
 * Left out: grape juice and wine concentrates, hopped malt-extract kits, spirit yeasts,
 * equipment and merchandise.
 */
const WAS = ["WAS Homebrew"];
const CC = ["Craft Components"];
const BOTH = [...WAS, ...CC];

export const CATALOG: CatalogItem[] = [
  // GRAIN
  { name: "Barrett Burston Ale", type: "GRAIN", brand: "Barrett Burston", ebc: 5.75, potential: 1.037, notes: "EBC 4.5–7.0", suppliers: CC },
  { name: "Barrett Burston Caramel", type: "GRAIN", brand: "Barrett Burston", ebc: 45, potential: 1.035, notes: "EBC 30–60", suppliers: CC },
  { name: "Barrett Burston Distiller", type: "GRAIN", brand: "Barrett Burston", ebc: 3.5, potential: 1.037, notes: "EBC 3.0–4.0", suppliers: CC },
  { name: "Barrett Burston Extra Pale", type: "GRAIN", brand: "Barrett Burston", ebc: 3.3, potential: 1.037, notes: "EBC ≤ 3.3", suppliers: CC },
  { name: "Barrett Burston Pale", type: "GRAIN", brand: "Barrett Burston", ebc: 3.9, potential: 1.037, notes: "EBC 3.3–4.5", suppliers: CC },
  { name: "Barrett Burston Wheat", type: "GRAIN", brand: "Barrett Burston", ebc: 6, potential: 1.038, notes: "EBC ≤ 6.0", suppliers: CC },
  { name: "Black Rock Unhopped Light LME", type: "GRAIN", brand: "Black Rock", ebc: 7, potential: 1.036, notes: "Liquid extract · add at the boil", suppliers: CC },
  { name: "Black Rock Unhopped Wheat LME", type: "GRAIN", brand: "Black Rock", ebc: 5.9, potential: 1.036, notes: "Liquid extract · add at the boil", suppliers: CC },
  { name: "Blue Lake Rolled Barley", type: "GRAIN", brand: "Blue Lake Milling", ebc: 3, potential: 1.032, suppliers: CC },
  { name: "Blue Lake Rolled Oat", type: "GRAIN", brand: "Blue Lake Milling", ebc: 3, potential: 1.032, suppliers: CC },
  { name: "Blue Lake Rolled Wheat", type: "GRAIN", brand: "Blue Lake Milling", ebc: 3, potential: 1.034, suppliers: CC },
  { name: "Château Abbey", type: "GRAIN", brand: "Castle Malting", ebc: 45, potential: 1.036, notes: "EBC 45", suppliers: CC },
  { name: "Château Arome", type: "GRAIN", brand: "Castle Malting", ebc: 100, potential: 1.036, notes: "EBC 95–105", suppliers: CC },
  { name: "Château Biscuit", type: "GRAIN", brand: "Castle Malting", ebc: 50, potential: 1.036, notes: "EBC 50", suppliers: BOTH },
  { name: "Château Black", type: "GRAIN", brand: "Castle Malting", ebc: 1300, potential: 1.034, notes: "EBC 1300", suppliers: CC },
  { name: "Château Cafe", type: "GRAIN", brand: "Castle Malting", ebc: 500, potential: 1.035, notes: "EBC 500", suppliers: CC },
  { name: "Château Cara Arome", type: "GRAIN", brand: "Castle Malting", ebc: 90, potential: 1.035, notes: "EBC 80–100", suppliers: CC },
  { name: "Château Cara Belgium", type: "GRAIN", brand: "Castle Malting", ebc: 32.5, potential: 1.035, notes: "EBC 30–35", suppliers: CC },
  { name: "Château Cara Blond", type: "GRAIN", brand: "Castle Malting", ebc: 20, potential: 1.036, notes: "EBC 20", suppliers: CC },
  { name: "Château Cara Cafe", type: "GRAIN", brand: "Castle Malting", ebc: 400, potential: 1.032, notes: "EBC 350–450", suppliers: CC },
  { name: "Château Cara Clair", type: "GRAIN", brand: "Castle Malting", ebc: 9, potential: 1.036, notes: "EBC 9", suppliers: BOTH },
  { name: "Château Cara Crystal", type: "GRAIN", brand: "Castle Malting", ebc: 150, potential: 1.034, notes: "EBC 140–160", suppliers: CC },
  { name: "Château Cara Gold", type: "GRAIN", brand: "Castle Malting", ebc: 120, potential: 1.036, notes: "EBC 120", suppliers: CC },
  { name: "Château Cara Honey", type: "GRAIN", brand: "Castle Malting", ebc: 70, potential: 1.035, notes: "EBC 60–80", suppliers: CC },
  { name: "Château Cara Ruby", type: "GRAIN", brand: "Castle Malting", ebc: 50, potential: 1.036, notes: "EBC 50", suppliers: CC },
  { name: "Château Cara Terra", type: "GRAIN", brand: "Castle Malting", ebc: 195, potential: 1.034, notes: "EBC 170–220", suppliers: CC },
  { name: "Château Chocolat", type: "GRAIN", brand: "Castle Malting", ebc: 1000, potential: 1.035, notes: "EBC 1000", suppliers: BOTH },
  { name: "Château Crystal", type: "GRAIN", brand: "Castle Malting", ebc: 150, potential: 1.034, notes: "EBC 150", suppliers: BOTH },
  { name: "Château Distilling", type: "GRAIN", brand: "Castle Malting", ebc: 5.5, potential: 1.038, notes: "EBC 4.5–6.5", suppliers: CC },
  { name: "Château Flaked Barley", type: "GRAIN", brand: "Castle Malting", ebc: 5, potential: 1.036, notes: "EBC 3–7", suppliers: CC },
  { name: "Château Flaked Barley Nature", type: "GRAIN", brand: "Castle Malting", ebc: 5, potential: 1.033, notes: "EBC 3–7", suppliers: CC },
  { name: "Château Flaked Maize (Corn)", type: "GRAIN", brand: "Castle Malting", ebc: 3.5, potential: 1.038, notes: "EBC 3–4", suppliers: CC },
  { name: "Château Flaked Oat", type: "GRAIN", brand: "Castle Malting", ebc: 4, potential: 1.032, notes: "EBC 3–5", suppliers: BOTH },
  { name: "Château Flaked Wheat", type: "GRAIN", brand: "Castle Malting", ebc: 7, potential: 1.036, notes: "EBC 5–9", suppliers: CC },
  { name: "Château Melano", type: "GRAIN", brand: "Castle Malting", ebc: 80, potential: 1.036, notes: "EBC 80", suppliers: CC },
  { name: "Château Melano Light", type: "GRAIN", brand: "Castle Malting", ebc: 40, potential: 1.036, notes: "EBC 40", suppliers: CC },
  { name: "Château Munich", type: "GRAIN", brand: "Castle Malting", ebc: 24.5, potential: 1.038, notes: "EBC 21–28", suppliers: CC },
  { name: "Château Munich Light", type: "GRAIN", brand: "Castle Malting", ebc: 15, potential: 1.038, notes: "EBC 13–17", suppliers: BOTH },
  { name: "Château Oat", type: "GRAIN", brand: "Castle Malting", ebc: 2.3, potential: 1.037, notes: "EBC 2.3", suppliers: CC },
  { name: "Château Pale Ale", type: "GRAIN", brand: "Castle Malting", ebc: 8.5, potential: 1.038, notes: "EBC 7–10", suppliers: BOTH },
  { name: "Château Peated", type: "GRAIN", brand: "Castle Malting", ebc: 4, potential: 1.037, notes: "EBC 4", suppliers: CC },
  { name: "Château Pilsen 2RS", type: "GRAIN", brand: "Castle Malting", ebc: 3.25, potential: 1.038, notes: "EBC 3.0–3.5", suppliers: BOTH },
  { name: "Château Pilsen 6RW", type: "GRAIN", brand: "Castle Malting", ebc: 4, potential: 1.037, notes: "EBC ≤ 4", suppliers: CC },
  { name: "Château Red Intense", type: "GRAIN", brand: "Castle Malting", ebc: 36, potential: 1.036, notes: "EBC 34.0–38.0", suppliers: CC },
  { name: "Château Roasted Barley", type: "GRAIN", brand: "Castle Malting", ebc: 1200, potential: 1.03, notes: "EBC 1000–1400", suppliers: BOTH },
  { name: "Château Rye", type: "GRAIN", brand: "Castle Malting", ebc: 5.5, potential: 1.038, notes: "EBC 3–8", suppliers: CC },
  { name: "Château Smoked", type: "GRAIN", brand: "Castle Malting", ebc: 8, potential: 1.036, notes: "EBC 4–12", suppliers: CC },
  { name: "Château Special B", type: "GRAIN", brand: "Castle Malting", ebc: 300, potential: 1.036, notes: "EBC 300", suppliers: CC },
  { name: "Château Vienna", type: "GRAIN", brand: "Castle Malting", ebc: 5.5, potential: 1.038, notes: "EBC 4–7", suppliers: CC },
  { name: "Château Wheat", type: "GRAIN", brand: "Castle Malting", ebc: 5.5, potential: 1.038, notes: "EBC 5.5", suppliers: CC },
  { name: "Château Wheat Black", type: "GRAIN", brand: "Castle Malting", ebc: 1250, potential: 1.036, notes: "EBC 1100–1400", suppliers: CC },
  { name: "Château Wheat Blanc", type: "GRAIN", brand: "Castle Malting", ebc: 4.5, potential: 1.038, notes: "EBC 3.5–5.5", suppliers: WAS },
  { name: "Château Wheat Chocolat", type: "GRAIN", brand: "Castle Malting", ebc: 950, potential: 1.036, notes: "EBC 800–1100", suppliers: CC },
  { name: "Château Wheat Crystal", type: "GRAIN", brand: "Castle Malting", ebc: 150, potential: 1.036, notes: "EBC 150", suppliers: CC },
  { name: "Château Wheat Munich Light", type: "GRAIN", brand: "Castle Malting", ebc: 16, potential: 1.038, notes: "EBC 14–18", suppliers: CC },
  { name: "Light Dried Malt Extract (DME)", type: "GRAIN", brand: "Muntons", ebc: 15, potential: 1.044, notes: "EBC 10–20 · add at the boil", suppliers: WAS },
  { name: "Thomas Fawcett Golden Promise", type: "GRAIN", brand: "Thomas Fawcett", ebc: 5.5, potential: 1.037, suppliers: CC },
  { name: "Thomas Fawcett Oat Malt", type: "GRAIN", brand: "Thomas Fawcett", ebc: 5, potential: 1.034, suppliers: CC },
  { name: "Thomas Fawcett Pale Chocolate", type: "GRAIN", brand: "Thomas Fawcett", ebc: 600, potential: 1.03, suppliers: CC },
  { name: "Torrefied Flaked Barley", type: "GRAIN", brand: "Micronizing India", ebc: 3, potential: 1.033, suppliers: CC },
  { name: "Torrefied Flaked Maize", type: "GRAIN", brand: "Micronizing India", ebc: 2, potential: 1.037, suppliers: CC },
  { name: "Torrefied Flaked Oat", type: "GRAIN", brand: "Micronizing India", ebc: 3, potential: 1.032, suppliers: CC },
  { name: "Torrefied Flaked Wheat", type: "GRAIN", brand: "Micronizing India", ebc: 3, potential: 1.035, suppliers: CC },
  // HOP
  { name: "Amarillo", type: "HOP", brand: "Virgil Gamache Farm", alphaAcid: 6.5, form: "Pellet", notes: "AA 6.5% · crop 2025", suppliers: CC },
  { name: "Azacca", type: "HOP", brand: "Roy Farms", alphaAcid: 12, form: "Pellet", notes: "AA 12% · crop 2023", suppliers: CC },
  { name: "Bramling Cross", type: "HOP", brand: "Charles Faram", alphaAcid: 6.4, form: "Pellet", notes: "AA 5–7.8% · crop 2025", suppliers: CC },
  { name: "Cascade", type: "HOP", brand: "Hollingbery & Son", alphaAcid: 5.6, form: "Pellet", notes: "AA 5.6% · crop 2025", suppliers: CC },
  { name: "Cascade Lupocore", type: "HOP", brand: "BarthHaas", alphaAcid: 9.5, form: "Cryo", notes: "AA 8–11% · crop 2025", suppliers: CC },
  { name: "Cashmere", type: "HOP", brand: "BarthHaas", alphaAcid: 8.1, form: "Pellet", notes: "AA 8.1% · crop 2025", suppliers: CC },
  { name: "Centennial", type: "HOP", brand: "BarthHaas", alphaAcid: 8.4, form: "Pellet", notes: "AA 8.4% · crop 2025", suppliers: BOTH },
  { name: "Centennial Lupocore", type: "HOP", brand: "BarthHaas", alphaAcid: 20, form: "Cryo", notes: "AA 18–22% · crop 2025", suppliers: CC },
  { name: "Challenger", type: "HOP", brand: "Charles Faram", alphaAcid: 7.8, form: "Pellet", notes: "AA 6.5–9% · crop 2025", suppliers: CC },
  { name: "Chinook", type: "HOP", brand: "Hollingbery & Son", alphaAcid: 11.9, form: "Pellet", notes: "AA 11.9% · crop 2025", suppliers: CC },
  { name: "Citra", type: "HOP", brand: "Yakima Chief", alphaAcid: 13.4, form: "Pellet", notes: "AA 13.4% · crop 2025", suppliers: BOTH },
  { name: "Citra Lupocore", type: "HOP", brand: "BarthHaas", alphaAcid: 20, form: "Cryo", notes: "AA 18–22% · crop 2025", suppliers: CC },
  { name: "Citra Lupomax", type: "HOP", brand: "BarthHaas", alphaAcid: 18.5, form: "Cryo", notes: "AA 17–20% · crop 2025", suppliers: CC },
  { name: "Columbus", type: "HOP", brand: "BarthHaas", alphaAcid: 13.9, form: "Pellet", notes: "AA 13.9% · crop 2025", suppliers: CC },
  { name: "CTZ Lupocore", type: "HOP", brand: "BarthHaas", alphaAcid: 20, form: "Cryo", notes: "AA 18–22% · crop 2025", suppliers: CC },
  { name: "East Kent Golding", type: "HOP", brand: "Charles Faram", alphaAcid: 5.8, form: "Pellet", notes: "AA 5–6.5% · crop 2025", suppliers: CC },
  { name: "El Dorado", type: "HOP", brand: "Hollingbery & Son", alphaAcid: 11.7, form: "Pellet", notes: "AA 11.7% · crop 2025", suppliers: CC },
  { name: "Elani", type: "HOP", brand: "Yakima Quality Hops", alphaAcid: 5.7, form: "Pellet", notes: "AA 5.7% · crop 2023", suppliers: CC },
  { name: "Fuggle", type: "HOP", brand: "Charles Faram", alphaAcid: 4.3, form: "Pellet", notes: "AA 2.4–6.1% · crop 2025", suppliers: BOTH },
  { name: "Green Bullet", type: "HOP", brand: "NZ Hops", alphaAcid: 12.5, form: "Pellet", notes: "AA 11–14% · crop 2026", suppliers: CC },
  { name: "Hallertau Blanc", type: "HOP", brand: "Charles Faram", alphaAcid: 10.5, form: "Pellet", notes: "AA 9–12% · crop 2025", suppliers: CC },
  { name: "Hallertau Hersbrucker", type: "HOP", brand: "Charles Faram", alphaAcid: 3.5, form: "Pellet", notes: "AA 2–5% · crop 2025", suppliers: CC },
  { name: "Hallertau Melon", type: "HOP", brand: "Charles Faram", alphaAcid: 7.2, form: "Pellet", notes: "AA 6.9–7.5% · crop 2025", suppliers: CC },
  { name: "Hallertau Mittelfrüh", type: "HOP", brand: "Charles Faram", alphaAcid: 4.3, form: "Pellet", notes: "AA 3–5.5% · crop 2025", suppliers: BOTH },
  { name: "Hallertau Tradition", type: "HOP", brand: "Charles Faram", alphaAcid: 5.8, form: "Pellet", notes: "AA 4.6–7% · crop 2025", suppliers: CC },
  { name: "Harlequin", type: "HOP", brand: "Charles Faram", alphaAcid: 10.8, form: "Pellet", notes: "AA 9.5–12% · crop 2023", suppliers: CC },
  { name: "HBC 1019", type: "HOP", brand: "BarthHaas", alphaAcid: 8.7, form: "Pellet", notes: "AA 8.7% · crop 2023", suppliers: CC },
  { name: "Idaho 7", type: "HOP", brand: "Hollingbery & Son", alphaAcid: 12.5, form: "Pellet", notes: "AA 10–14.9% · crop 2025", suppliers: CC },
  { name: "Jester", type: "HOP", brand: "Charles Faram", alphaAcid: 8, form: "Pellet", notes: "AA 7–9% · crop 2024", suppliers: CC },
  { name: "Krush HBC 586", type: "HOP", brand: "Yakima Chief", alphaAcid: 13.5, form: "Pellet", notes: "AA 12–15% · crop 2025", suppliers: CC },
  { name: "Magnum", type: "HOP", brand: "Charles Faram", alphaAcid: 12, form: "Pellet", notes: "AA 10–14% · crop 2025", suppliers: CC },
  { name: "McKenzie", type: "HOP", brand: "BarthHaas", alphaAcid: 11.7, form: "Pellet", notes: "AA 11.7% · crop 2023", suppliers: CC },
  { name: "Mosaic", type: "HOP", brand: "Yakima Chief", alphaAcid: 13.9, form: "Pellet", notes: "AA 13.9% · crop 2025", suppliers: BOTH },
  { name: "Mosaic Lupocore", type: "HOP", brand: "BarthHaas", alphaAcid: 20, form: "Cryo", notes: "AA 18–22% · crop 2025", suppliers: CC },
  { name: "Mosaic Lupomax", type: "HOP", brand: "BarthHaas", alphaAcid: 18.8, form: "Cryo", notes: "AA 17.5–20% · crop 2025", suppliers: CC },
  { name: "Motueka", type: "HOP", brand: "NZ Hops", alphaAcid: 7.8, form: "Pellet", notes: "AA 5.5–10% · crop 2026", suppliers: CC },
  { name: "Moutere", type: "HOP", brand: "NZ Hops", alphaAcid: 16.8, form: "Pellet", notes: "AA 15.5–18% · crop 2023", suppliers: CC },
  { name: "Nectaron", type: "HOP", brand: "NZ Hops", alphaAcid: 12, form: "Pellet", notes: "AA 10–14% · crop 2026", suppliers: CC },
  { name: "Nelson Sauvin", type: "HOP", brand: "NZ Hops", alphaAcid: 11.5, form: "Pellet", notes: "AA 10–13% · crop 2026", suppliers: CC },
  { name: "Northern Brewer", type: "HOP", brand: "Charles Faram", alphaAcid: 8.5, form: "Pellet", notes: "AA 7–10% · crop 2025", suppliers: CC },
  { name: "Nugget", type: "HOP", brand: "BarthHaas", alphaAcid: 11.8, form: "Pellet", notes: "AA 9.5–14% · crop 2022", suppliers: CC },
  { name: "Olicana", type: "HOP", brand: "Charles Faram", alphaAcid: 8, form: "Pellet", notes: "AA 7–9% · crop 2023", suppliers: CC },
  { name: "Pacifica", type: "HOP", brand: "NZ Hops", alphaAcid: 5.5, form: "Pellet", notes: "AA 5–6% · crop 2026", suppliers: CC },
  { name: "Perle", type: "HOP", brand: "Charles Faram", alphaAcid: 8.5, form: "Pellet", notes: "AA 8–9% · crop 2025", suppliers: CC },
  { name: "Riwaka", type: "HOP", brand: "NZ Hops", alphaAcid: 5.5, form: "Pellet", notes: "AA 4.5–6.5% · crop 2026", suppliers: CC },
  { name: "Saaz", type: "HOP", brand: "Charles Faram", alphaAcid: 3.5, form: "Pellet", notes: "AA 2.5–4.5% · crop 2025", suppliers: BOTH },
  { name: "Simcoe", type: "HOP", brand: "Yakima Chief", alphaAcid: 13, form: "Pellet", notes: "AA 12–14% · crop 2025", suppliers: BOTH },
  { name: "Sorachi Ace", type: "HOP", brand: "BSG", alphaAcid: 9.7, form: "Pellet", notes: "AA 9.7% · crop 2023", suppliers: CC },
  { name: "Southern Cross", type: "HOP", brand: "NZ Hops", alphaAcid: 12.5, form: "Pellet", notes: "AA 11–14% · crop 2026", suppliers: CC },
  { name: "Strata", type: "HOP", brand: "Yakima Chief", alphaAcid: 13, form: "Pellet", notes: "AA 11–15% · crop 2025", suppliers: CC },
  { name: "Superdelic", type: "HOP", brand: "NZ Hops", alphaAcid: 9.8, form: "Pellet", notes: "AA 9–10.5% · crop 2026", suppliers: CC },
  { name: "Taiheke", type: "HOP", brand: "NZ Hops", alphaAcid: 7, form: "Pellet", notes: "AA 6–8% · crop 2026", suppliers: CC },
  { name: "Target", type: "HOP", brand: "Charles Faram", alphaAcid: 10.3, form: "Pellet", notes: "AA 8–12.5% · crop 2025", suppliers: CC },
  { name: "Tettnang", type: "HOP", brand: "Charles Faram", alphaAcid: 4.4, form: "Pellet", notes: "AA 3–5.8% · crop 2025", suppliers: BOTH },
  { name: "UK Golding", type: "HOP", brand: "Yakima Chief", alphaAcid: 5.5, form: "Pellet", notes: "AA 5–6%", suppliers: WAS },
  { name: "Vista", type: "HOP", brand: "BarthHaas", alphaAcid: 11.5, form: "Pellet", notes: "AA 11–12% · crop 2023", suppliers: CC },
  { name: "Wai-iti", type: "HOP", brand: "NZ Hops", alphaAcid: 2.8, form: "Pellet", notes: "AA 2–3.5% · crop 2026", suppliers: CC },
  { name: "Waimea", type: "HOP", brand: "NZ Hops", alphaAcid: 17.5, form: "Pellet", notes: "AA 16–19% · crop 2026", suppliers: CC },
  { name: "Wakatu", type: "HOP", brand: "NZ Hops", alphaAcid: 7.5, form: "Pellet", notes: "AA 6.5–8.5% · crop 2023", suppliers: CC },
  // YEAST
  { name: "LalBrew Voss Kveik", type: "YEAST", brand: "Lallemand", form: "Dry", attenuation: 79, flocculation: "High", notes: "25–40 °C, best at 35–40 °C", suppliers: WAS },
  { name: "Lalvin 71B", type: "YEAST", brand: "Lallemand", form: "Dry", notes: "Wine / cider", suppliers: WAS },
  { name: "Lalvin EC-1118", type: "YEAST", brand: "Lallemand", form: "Dry", notes: "Wine / cider", suppliers: WAS },
  { name: "M05 Mead", type: "YEAST", brand: "Mangrove Jack's", form: "Dry", notes: "Mead", suppliers: WAS },
  { name: "M20 Bavarian Wheat", type: "YEAST", brand: "Mangrove Jack's", form: "Dry", attenuation: 74, flocculation: "Low", suppliers: WAS },
  { name: "M31 Belgian Tripel", type: "YEAST", brand: "Mangrove Jack's", form: "Dry", attenuation: 84, flocculation: "Medium", suppliers: WAS },
  { name: "M66 Hophead Ale", type: "YEAST", brand: "Mangrove Jack's", form: "Dry", attenuation: 80, flocculation: "Medium", suppliers: WAS },
  { name: "Safale BE-134", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 91, flocculation: "Low", notes: "Saison Ale", suppliers: CC },
  { name: "Safale BE-256", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 84, flocculation: "High", notes: "Belgian Abbaye Ale", suppliers: CC },
  { name: "Safale BW-20", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 80, flocculation: "Medium", notes: "Belgian Ale", suppliers: CC },
  { name: "Safale K-97", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 82, flocculation: "Low", notes: "Session Ale", suppliers: CC },
  { name: "Safale S-04", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 78, flocculation: "High", notes: "English Ale", suppliers: CC },
  { name: "Safale S-33", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 75, flocculation: "Medium", notes: "Hoppy Style Ale", suppliers: CC },
  { name: "Safale T-58", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 75, flocculation: "Medium", notes: "Strong Belgian Style", suppliers: CC },
  { name: "Safale US-05", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 80, flocculation: "Medium", notes: "American Ale", suppliers: BOTH },
  { name: "Safale W-68", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 81, flocculation: "Medium", notes: "German Wheat Style", suppliers: CC },
  { name: "Safale WB-06", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 88, flocculation: "Low", notes: "Wheat Base Beer", suppliers: CC },
  { name: "SafBrew LA-01", type: "YEAST", brand: "Fermentis", form: "Dry", flocculation: "Medium", notes: "Low/ No Alcohol", suppliers: CC },
  { name: "SafCider AB-1", type: "YEAST", brand: "Fermentis", form: "Dry", notes: "Neutral Cider", suppliers: CC },
  { name: "SafCider AC-4", type: "YEAST", brand: "Fermentis", form: "Dry", notes: "Intense Aromatic Cider", suppliers: CC },
  { name: "SafCider AS-2", type: "YEAST", brand: "Fermentis", form: "Dry", notes: "Sweet and Complex Cider", suppliers: CC },
  { name: "SafCider TF-6", type: "YEAST", brand: "Fermentis", form: "Dry", notes: "Fruity Cider", suppliers: CC },
  { name: "Saflager E-30", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 72, flocculation: "High", notes: "Estery Lager", suppliers: CC },
  { name: "Saflager S-189", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 82, flocculation: "High", notes: "Cleanest Lager", suppliers: BOTH },
  { name: "Saflager S-23", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 82, flocculation: "High", notes: "Hoppy Lager", suppliers: BOTH },
  { name: "Saflager W-34/70", type: "YEAST", brand: "Fermentis", form: "Dry", attenuation: 82, flocculation: "High", notes: "Bohemian Lager", suppliers: CC },
  // WATER
  { name: "Calcium Chloride (CaCl2)", type: "WATER", waterSalt: "CaCl2", suppliers: WAS },
  { name: "Epsom Salt (MgSO4)", type: "WATER", waterSalt: "MgSO4", suppliers: WAS },
  { name: "Gypsum (CaSO4)", type: "WATER", waterSalt: "CaSO4", suppliers: WAS },
  { name: "Lactic Acid", type: "WATER", notes: "Lowers mash / sparge pH", suppliers: BOTH },
  { name: "Sodium Bicarbonate (NaHCO3)", type: "WATER", waterSalt: "NaHCO3", notes: "Baking soda", suppliers: WAS },
  // OTHER
  { name: "Bitter Orange Peel", type: "OTHER", notes: "Spice · end of boil", suppliers: CC },
  { name: "Château Rice Hulls", type: "OTHER", brand: "Castle Malting", notes: "Lautering aid, no extract", suppliers: CC },
  { name: "Cocoa Husks", type: "OTHER", notes: "Spice · secondary or end of boil", suppliers: CC },
  { name: "Dextrose", type: "OTHER", potential: 1.046, notes: "Corn sugar · priming or boil", suppliers: BOTH },
  { name: "Irish Moss", type: "OTHER", suppliers: WAS },
  { name: "Lactose", type: "OTHER", potential: 1.035, unfermentable: true, notes: "Milk sugar · adds sweetness and body", suppliers: CC },
  { name: "Lemon Peel", type: "OTHER", notes: "Spice · end of boil", suppliers: CC },
  { name: "Malic Acid", type: "OTHER", notes: "Cider / wine acidity", suppliers: CC },
  { name: "Maltodextrin", type: "OTHER", potential: 1.04, unfermentable: true, notes: "Adds body", suppliers: CC },
  { name: "SpringFerm Xtrem", type: "OTHER", brand: "Fermentis", notes: "Yeast nutrient", suppliers: CC },
  { name: "Sweet Orange Peel", type: "OTHER", notes: "Spice · end of boil", suppliers: CC },
  { name: "Whirlfloc Tablets", type: "OTHER", notes: "Kettle fining · 1 tablet per 20 L, last 5 min", suppliers: CC },
  { name: "Yeast Nutrient (DAP)", type: "OTHER", suppliers: WAS },
];
